createSecret: true
createRedisSecret: true
createPostgresqlSecret: true

host: defectdojo.tawa.local

django:
  ingress:
    enabled: true
    ingressClassName: nginx
    activateTLS: true

admin:
  user: admin
  password:
  firstName: Administrator
  lastName: User
  mail: admin@defectdojo.local

alternativeHosts:
  - defectdojo-django.defectdojo.svc.cluster.local
