## Below settings are a copy from Trivy Operator v0.23.0 default settings. They are not been changed.
### Source: https://github.com/aquasecurity/trivy-operator/blob/v0.27.3/deploy/helm/values.yaml
### App ver: 0.27.3 // Chart ver: 0.29.3

##--------- Set default Trivy config ----------##
serviceMonitor:
  # -- enabled determines whether a serviceMonitor should be deployed
  enabled: true

trivy:
  image:
    # -- registry of the Trivy image
    registry: mirror.gcr.io
    # -- repository of the Trivy image
    repository: aquasec/trivy
    # -- tag version of the Trivy image
    tag: 0.63.0
    # -- imagePullSecret is the secret name to be used when pulling trivy image from private registries example : reg-secret
    # It is the user responsibility to create the secret for the private registry in `trivy-operator` namespace
    imagePullSecret: ~
    # -- pullPolicy is the imge pull policy used for trivy image , valid values are (Always, Never, IfNotPresent)
    pullPolicy: IfNotPresent
  # true: view only fixed vulns (equivalent to 'trivy image --ignore-unfixed ...')
  # false: view all (fixed and unfixed) vulns
  ignoreUnfixed: false

service:
  # -- disabled ensures that the pod gets a ClusterIP.
  headless: false

operator:
  # -- builtInTrivyServer The flag enables the usage of built-in trivy server in cluster. It also overrides the following trivy params with built-in values
  # trivy.mode = ClientServer and serverURL = http://<serverServiceName>.<trivy operator namespace>:4975
  builtInTrivyServer: true

  # -- the flag to enable vulnerability scanner
  vulnerabilityScannerEnabled: true
  # -- the flag to enable sbom generation, required for enabling ClusterVulnerabilityReports
  sbomGenerationEnabled: false
  # -- the flag to enable cluster sbom cache generation
  clusterSbomCacheEnabled: false
  # -- scannerReportTTL the flag to set how long a report should exist. "" means that the ScannerReportTTL feature is disabled
  scannerReportTTL: "24h"
  # -- cacheReportTTL the flag to set how long a cluster sbom report should exist. "" means that the cacheReportTTL feature is disabled
  cacheReportTTL: "120h"
  # -- configAuditScannerEnabled the flag to enable configuration audit scanner
  configAuditScannerEnabled: false
  # -- rbacAssessmentScannerEnabled the flag to enable rbac assessment scanner
  rbacAssessmentScannerEnabled: false
  # -- infraAssessmentScannerEnabled the flag to enable infra assessment scanner
  infraAssessmentScannerEnabled: true
  # -- clusterComplianceEnabled the flag to enable cluster compliance scanner
  clusterComplianceEnabled: true
  # -- batchDeleteLimit the maximum number of configaudit reports deleted by the operator when the plugin's config has changed.
  batchDeleteLimit: 10
  # -- vulnerabilityScannerScanOnlyCurrentRevisions the flag to only create vulnerability scans on the current revision of a deployment.
  vulnerabilityScannerScanOnlyCurrentRevisions: true
  # -- configAuditScannerScanOnlyCurrentRevisions the flag to only create configaudit scans on the current revision of a deployment.
  configAuditScannerScanOnlyCurrentRevisions: true
  # -- batchDeleteDelay the duration to wait before deleting another batch of configaudit reports.
  batchDeleteDelay: 10s
  # -- accessGlobalSecretsAndServiceAccount The flag to enable access to global secrets/service accounts to allow `vulnerability scan job` to pull images from private registries
  accessGlobalSecretsAndServiceAccount: true

  ##------------ Get Findings Details --------------##
  # By default all of them are false, be aware of metrics cardinality when
  # setting to true, except exposedSecretScannerEnabled (default true)
  # They'll be enabled/disabled during the metrics cardinality evaluation
  metricsVulnIdEnabled: true
  exposedSecretScannerEnabled: true
  metricsExposedSecretInfo: true
  metricsConfigAuditInfo: false
  metricsRbacAssessmentInfo: false
  metricsInfraAssessmentInfo: true
  metricsImageInfo: true
  metricsClusterComplianceInfo: true

image:
  registry: mirror.gcr.io
  repository: aquasec/trivy-operator
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

compliance:
  ##---------------- Compliance assessment config -----------------##
  # -- cron this flag control the cron interval for compliance report generation
  # Every day at 12h
  #cron: 0 12 * * *
  cron: 50 */1 * * *
  specs:
    - k8s-cis-1.23
    - k8s-nsa-1.0
    - k8s-pss-baseline-0.1
    - k8s-pss-restricted-0.1
    - eks-cis-1.4