---
# Global settings
# create defectdojo specific secret
createSecret: true
# create redis secret in defectdojo chart, outside of redis chart
createRedisSecret: true
# create postgresql secret in defectdojo chart, outside of postgresql chart
createPostgresqlSecret: true

host: defectdojo.tawa.local

django:
  ingress:
    enabled: true
    ingressClassName: nginx
    activateTLS: true

admin:
  user: admin
  password:
  firstName: Administrator
  lastName: User
  mail: admin@defectdojo.local
