---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-scan-cm-policies
data:
  my-policy-01: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <configuration>
        <policy>my-policy-01</policy>
        <scanner>
            <level>MEDIUM</level>
            <strength>MEDIUM</strength>
        </scanner>
        <plugins>
            <p6>
                <enabled>true</enabled>
            </p6>
            <p7>
                <enabled>true</enabled>
            </p7>
            <p10045>
                <enabled>false</enabled>
                <level>OFF</level>
                <strength>DEFAULT</strength>
            </p10045>
            <p20015>
                <enabled>true</enabled>
            </p20015>
            <p20017>
                <enabled>true</enabled>
            </p20017>
            <p20018>
                <enabled>true</enabled>
            </p20018>
            <p20019>
                <enabled>true</enabled>
            </p20019>
            <p40009>
                <enabled>true</enabled>
            </p40009>
            <p40012>
                <enabled>true</enabled>
            </p40012>
            <p40014>
                <enabled>true</enabled>
            </p40014>
            <p40018>
                <enabled>true</enabled>
            </p40018>
            <p40019>
                <enabled>false</enabled>
                <level>OFF</level>
            </p40019>
            <p40020>
                <enabled>false</enabled>
                <level>OFF</level>
            </p40020>
            <p40021>
                <enabled>false</enabled>
                <level>OFF</level>
            </p40021>
            <p40022>
                <enabled>true</enabled>
            </p40022>
            <p40024>
                <enabled>false</enabled>
                <level>OFF</level>
            </p40024>
            <p40026>
                <enabled>true</enabled>
                <level>DEFAULT</level>
                <strength>DEFAULT</strength>
            </p40026>
            <p40027>
                <enabled>false</enabled>
                <level>OFF</level>
            </p40027>
            <p40043>
                <enabled>true</enabled>
            </p40043>
            <p40045>
                <enabled>true</enabled>
            </p40045>
            <p90019>
                <enabled>true</enabled>
            </p90019>
            <p90020>
                <enabled>true</enabled>
            </p90020>
            <p90021>
                <enabled>false</enabled>
                <level>OFF</level>
            </p90021>
            <p90023>
                <enabled>false</enabled>
                <level>OFF</level>
            </p90023>
            <p90024>
                <enabled>true</enabled>
            </p90024>
            <p90034>
                <enabled>true</enabled>
            </p90034>
            <p90035>
                <enabled>true</enabled>
            </p90035>
            <p90036>
                <enabled>true</enabled>
            </p90036>
            <p0>
                <enabled>true</enabled>
            </p0>
            <p30001>
                <enabled>true</enabled>
            </p30001>
            <p30002>
                <enabled>true</enabled>
            </p30002>
            <p40003>
                <enabled>true</enabled>
            </p40003>
            <p40008>
                <enabled>true</enabled>
            </p40008>
            <p40028>
                <enabled>true</enabled>
            </p40028>
            <p40029>
                <enabled>true</enabled>
            </p40029>
            <p40032>
                <enabled>true</enabled>
            </p40032>
            <p40034>
                <enabled>true</enabled>
            </p40034>
            <p40035>
                <enabled>true</enabled>
            </p40035>
            <p40042>
                <enabled>true</enabled>
            </p40042>
            <p90017>
                <enabled>false</enabled>
                <level>OFF</level>
            </p90017>
            <p10058>
                <enabled>true</enabled>
            </p10058>
            <p10104>
                <enabled>true</enabled>
            </p10104>
            <p40016>
                <enabled>true</enabled>
            </p40016>
            <p40017>
                <enabled>true</enabled>
            </p40017>
            <p50000>
                <enabled>true</enabled>
            </p50000>
            <p90026>
                <enabled>false</enabled>
                <level>OFF</level>
            </p90026>
            <p90029>
                <enabled>false</enabled>
                <level>OFF</level>
            </p90029>
        </plugins>
    </configuration>
  my-policy-02: |
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <configuration>
        <policy>my-policy-02</policy>
        <scanner>
            <level>OFF</level>
            <strength>MEDIUM</strength>
        </scanner>
        <plugins>
            <p20019>
                <name>External Redirect</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p20019>
            <p40012>
                <name>Cross Site Scripting (Reflected)</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p40012>
            <p40018>
                <name>SQL Injection</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p40018>
            <p50000>
                <name>Script Active Scan Rules</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p50000>
            <p90017>
                <name>XSLT Injection</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p90017>
            <p90020>
                <name>Remote OS Command Injection</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p90020>
            <p90021>
                <name>XPath Injection</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p90021>
            <p90023>
                <name>XML External Entity Attack</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p90023>
            <p90026>
                <name>SOAP Action Spoofing</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p90026>
            <p90029>
                <name>SOAP XML Injection</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p90029>
            <p90035>
                <name>Server Side Template Injection</name>
                <enabled>true</enabled>
                <level>MEDIUM</level>
            </p90035>
        </plugins>
    </configuration>
---